"""Change item_id to item_ingame_id

Revision ID: aa481876f47b
Revises: eb355ea8cd3a
Create Date: 2024-12-11 18:26:30.597809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa481876f47b'
down_revision: Union[str, None] = 'eb355ea8cd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('item_ingame_id', sa.Integer(), nullable=False))
    op.drop_constraint('properties_item_id_fkey', 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'item', ['item_ingame_id'], ['ingame_id'])
    op.drop_column('properties', 'item_id')
    op.add_column('skill', sa.Column('item_ingame_id', sa.Integer(), nullable=False))
    op.drop_constraint('skill_item_id_fkey', 'skill', type_='foreignkey')
    op.create_foreign_key(None, 'skill', 'item', ['item_ingame_id'], ['ingame_id'])
    op.drop_column('skill', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.create_foreign_key('skill_item_id_fkey', 'skill', 'item', ['item_id'], ['ingame_id'])
    op.drop_column('skill', 'item_ingame_id')
    op.add_column('properties', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key('properties_item_id_fkey', 'properties', 'item', ['item_id'], ['ingame_id'])
    op.drop_column('properties', 'item_ingame_id')
    # ### end Alembic commands ###
