"""Initial migration

Revision ID: eb355ea8cd3a
Revises: 
Create Date: 2024-12-10 20:38:11.283914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb355ea8cd3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingame_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('damage_type', sa.Enum('PHYSICAL', 'FIRE', 'ICE', 'ENERGY', 'LIGHT', 'POISON', 'NONE', name='damagetype'), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingame_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_lvl', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('max_lvl_damage', sa.Integer(), nullable=True),
    sa.Column('max_lvl_ammo', sa.Integer(), nullable=True),
    sa.Column('max_lvl_atk_speed', sa.Float(), nullable=True),
    sa.Column('max_lvl_hp', sa.Integer(), nullable=True),
    sa.Column('weapon_type', sa.Enum('AUTO_RIFLE', 'MELEE', 'PISTOL', 'HEAVY_PISTOL', 'DEPLOY_ANCIENT', 'DEPLOY_BATTERY', 'DEPLOY_DOLLY', 'DEPLOY_TRAP', 'DEPLOY_MINE', 'DEPLOY_SPECIAL', 'RPG', 'SPREAD_SHOTGUN', 'SINGLE_SHOTGUN', 'SNIPER_RIFLE', 'SPECIAL', 'BOW', 'SPRAY', 'ACTIVATE_SPRAY', 'SWITCH_SPRAY', 'THROWN', name='weapontype'), nullable=True),
    sa.Column('deploy_limit', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('crit_rate', sa.Float(), nullable=True),
    sa.Column('base_sync', sa.Integer(), nullable=True),
    sa.Column('max_sync', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.ingame_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingame_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description_template_id', sa.Integer(), nullable=False),
    sa.Column('description_template', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('damage_type', sa.Enum('PHYSICAL', 'FIRE', 'ICE', 'ENERGY', 'LIGHT', 'POISON', 'NONE', name='damagetype'), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.ingame_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    op.drop_table('properties')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('item')
    # ### end Alembic commands ###
